### ISSUE TITLE
The API does not work now

### ISSUE THREAD

**Issue by stonycat** [phucty/mtab_tool#1]
Hi~
I want to build a system related to using an external knowledge base to provide useful information for end-users. I found your API is suitable for my project and I want to cite your work. However, the API of search entity does not work now. I try to ask for help and figure out the reason.

**Comment by phucty** [comment]
Hi StonyCat,
Thank you for your interest.
It works now. Enjoy. 
If you have any questions, please let me know. 

Thanks
