### ISSUE TITLE
API connection refused

### ISSUE THREAD

**Issue by Betty1202** [phucty/mtab_tool#4]
Hello~ The [API](https://mtab.app/api/v1/mtab) worked fine yesterday, but today the connection was rejected.
I annotated a table with `curl -X POST -F file=@"0.t0.csv" https://mtab.app/api/v1/mtab`, but got `curl: (7) Failed to connect to mtab.app port 443: Connection refused`. And [inference ](https://mtab.app/mtab) can't be opened, too.

**Comment by phucty** [comment]
Hi @Betty1202 ,
Thank you for your message.
I am sorry for this inconvenience, our server was down for a while. I restarted MTab services, so the API should work now. 

If there is any problem with API, please let me know. 
Thank you very much.

Regards,
Phuc

**Comment by Betty1202** [comment]
> Hi @Betty1202 , Thank you for your message. I am sorry for this inconvenience, our server was down for a while. I restarted MTab services, so the API should work now.
> 
> If there is any problem with API, please let me know. Thank you very much.
> 
> Regards, Phuc

It works. Thanks a lot~

**Comment by phucty** [comment]
Hi @Betty1202,
I reopened the issue since our servers are under maintenance (Network maintenance). MTab API could not be accessed during that time. The services will be available tomorrow. 

Thank you for your understanding.

Regards,

Phuc

**Comment by Betty1202** [comment]
@phucty Thanks~
Yesterday, I used your API to inference more than 50 batch, and one batch had about 90 tables. Maybe the problem with your servers is due to too many visits? If this is the reason, I am really sorry about that~

Best，
Betty

**Comment by phucty** [comment]
@Betty1202 No worry. 
At my working place, we have yearly maintenance of networks and power sources. It usually takes a day, then we can use our servers. I will check the servers and re-run MTab services tomorrow. 

Regards,

Phuc

**Comment by phucty** [comment]
All services are online now.

I close this issue. If there is any problem, please let me know. 

Thank
